#!/usr/bin/env node

require('shelljs/global');
const { readFileSync, writeFileSync } = require('fs');

var msg;
var file = process.argv[2];
var type = process.argv[3];
// current branch name
var branch = exec('git rev-parse --abbrev-ref HEAD').output;

if (type) return exit(0);

if(/COMMIT_EDITMSG/g.test(file)){
	const message = readFileSync(file, 'utf-8');
	msg = '#issue 123: \n'
        + '內容\n';
	writeFileSync(file, `${msg}`+`${message}`.replace(/\n/, ''));
}